#!/usr/bin/env python3
"""Rasterises the handful of glyphs painted on the road into src/roadglyphs.rs.

The PSP has no font to draw these from at boot, so they are baked here once, as 32 x 32 one-bit
bitmaps, and committed. Run it again only to change the glyphs:

    python3 scripts/road_glyphs.py

Needs Pillow and a Noto Sans CJK JP (any weight file that fontconfig can find).
"""
import subprocess
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

GLYPHS = "40急カーブ"
SIZE = 32


def font_path():
    out = subprocess.run(["fc-match", "-f", "%{file}", "Noto Sans CJK JP:bold"], capture_output=True, text=True)
    return out.stdout.strip()


def main():
    font = ImageFont.truetype(font_path(), 30)
    try:
        font.set_variation_by_name("Bold")
    except Exception:
        pass
    rows = []
    for g in GLYPHS:
        im = Image.new("L", (SIZE, SIZE), 0)
        d = ImageDraw.Draw(im)
        l, t, r, b = d.textbbox((0, 0), g, font=font)
        d.text(((SIZE - (r - l)) / 2 - l, (SIZE - (b - t)) / 2 - t), g, font=font, fill=255)
        bits = []
        for y in range(SIZE):
            word = 0
            for x in range(SIZE):
                if im.getpixel((x, y)) >= 128:
                    word |= 1 << x
            bits.append(word)
        rows.append((g, bits))
    out = [
        "//! Road-text glyphs, 32 x 32 one-bit, bit `x` of row `y` set where the paint is.",
        "//!",
        "//! Generated by `scripts/road_glyphs.py`; do not edit by hand.",
        "",
        f"pub const GLYPH_SIZE: usize = {SIZE};",
        "",
        "/// The glyphs, in the order `Glyph` names them.",
        f"pub const GLYPHS: [[u32; {SIZE}]; {len(rows)}] = [",
    ]
    for g, bits in rows:
        out.append(f"    // {g}")
        out.append("    [")
        for i in range(0, SIZE, 4):
            out.append("        " + " ".join(f"0x{w:08x}," for w in bits[i:i + 4]))
        out.append("    ],")
    out.append("];")
    Path("src/roadglyphs.rs").write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
